;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with ‘C-x C-f’ and enter text in its buffer.

;; Generated by ChatGPT on Friday, June 5, 2026

(defun comment-out-printfs ()
  "Comment out all printf statements in the current buffer, including
multi-line calls."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\\_<printf\\_>[[:space:]\n\r]*(" nil t)
      (let* ((start (save-excursion
                       (goto-char (match-beginning 0))
                       (skip-chars-backward " \t")
                       (point)))
             (end (save-excursion
                    ;; Point is just after the opening paren.
                    (goto-char (1- (point)))
                    (forward-sexp)      ; move past matching ')'
                    (skip-chars-forward " \t\n\r")
                    (when (looking-at ";")
                      (forward-char 1))
                    (point))))
        (comment-region start end)))))
